version: "3.9"

services:
  api01: &api
    hostname: api01
    image: avelfir/crebito:latest
    environment:
      - DB_HOSTNAME=db
      - JVM_XMS=150m
      - JVM_XMX=225m
      - CONTAINER_MEMORY=225m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=8m
      - MIN_HEAP_FREE_RATIO=30
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=3
      - MAX_POOL_CONNECTION=3
#      - PORT=3000
      - LOG_LEVEL=DEBUG
    ports:
      - "3001:8081"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "238MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - JVM_XMS=150m
      - JVM_XMX=225m
      - CONTAINER_MEMORY=225m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=8m
      - MIN_HEAP_FREE_RATIO=30
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=3
      - MAX_POOL_CONNECTION=3
#      - PORT=3000
    ports:
      - "3002:8081"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "12MB"
    networks:
      - default

  db:
    image:  postgres:15.3-bullseye
    container_name: db
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '62MB'
    ports:
      - "5433:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf:z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "rinha"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    networks:
      - default


networks:
  default:
    driver: bridge