server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non-contextual-creation: true