server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: admin
    password: 123
#  jpa:
#    hibernate:
#      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non-contextual-creation: true