server:
  port: ${PORT:20000}
  tomcat:
    max-threads: ${MAX_POOL_CONNECTION:4}
    max-connections: ${MAX_POOL_CONNECTION:4}

spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/rinha
    username: admin
    password: 123
    max-active: ${MAX_POOL_CONNECTION:4}
    min-active: ${MIN_POOL_CONNECTION:4}
    hikari:
      maximum-pool-size: ${MAX_POOL_CONNECTION:4}
      minimum-pool-size: ${MIN_POOL_CONNECTION:4}
    tomcat:
      max-active: ${MAX_POOL_CONNECTION:5}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  jackson:
    deserialization:
      accept-float-as-int: false

logging:
  level:
    com.ead: ${LOG_LEVEL:INFO}
    root: ${LOG_LEVEL:INFO}
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  info:
#    env:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
